String.toLocaleString({
	"en": {
		"%title": "English - l10n.js demo",
		"%info": "You are viewing an English localization of this page.",
		"%101": "Media Library Management",
		"%102": "Server Settings",
		"%103": "Switch User",
		"%104": "Sign Out",
		"%105": "Refresh",
		"%106": "Edit",
		"%107": "Delete",
		"%108": "Delete the selected media file from server?",
		"%109": "Refresh Accomplished!",
		"%110": "Media Name",
		"%111": "Media Type",
		"%112": "Media Path",
		"%113": "Browse",
		"%114": "Cancel",
		"%115": "OK",
		"%116": "Server Status",
		"%117": "General",
		"%118": "Media Library",
		"%119": "Transcoding",
		"%120": "Network",
		"%121": "Server Information",
		"%122": "Server Name",
		"%123": "Server Version",
		"%124": "Server IP",
		"%125": "WEB Port Number",
		"%126": "Real-time Server Info",
		"%127": "Client in Current Connection",
		"%128": "CPU Usage",
		"%129": "Remaining Memory",
		"%130": "Check for Update",
		"%131": "The name will be applied on this media server so that other networked computers can easily identify it. If you leave it blank, system will use your computer name by default.",
		"%132": "Add",
		"%133": "WEB Page Language",
		"%134": "Start server on Windows startup.",
		"%135": "Save",
		"%136": "Temporary File Path",
		"%137": "Set up a path to save temporary files while transcoding. The selected partition shall have a free space of no less than 1GB.",
		"%138": " Maximum CPU Usage",
		"%139": "Streaming media port",
		"%140": "Allow only this computer to access Web management page.",
		"%141": "If you set this option, then only the computers connected to VidOn server are allowed to access http://localhost:32080/ for server management.",
		"%142": "Web Port",
		"%143": "Set the accessing port number of Web management page",
		"%144": " Web Management Username",
		"%145": " Web Management Password",
		"%146": "The default value for username and password is null while logging into the Web management page.",
		"%147": " Media Library Auto-update Frequency",
		"%148": "Never",
		"%149": "Every one hour",
		"%150": "Every 12 hours",
		"%151": "Everyday",
		"%152": "Every three days",
		"%153": "Every week",
		"%154": "Every month",
		"%155": "Accessing movie information",
		"%156": "Information saved successfully",
		"%157": "Cancel basic information",
		"%158": "Cancel network settings",
		"%159": "Update all media resources",
		"%160": "Please input the target media path correctly",
		"%161": "Movie",
		"%162": "TV Show",
		"%163": "Video",
		"%164": "Image",
		"%165": "Add Media Resource",
		"%166": "Edit Media Resource",
		"%167": "Automatic",
		"%168": "File Browsing",
		"%169": "Check for Update",
		"%170": "Download Update",
		"%171": "Install",
		"%172": "Failed to download, please retry",
		"%173": "Your version is the latest",
		"%174": "Installation failed, please re-install",
		"%175": "Downloading",
		"%176": "Installing",
		"%177": "Update",
		"%178": "Update choices",
		"%179": "Auto",
		"%180": "Manual",
		"%181": "Update frequency:",
		"%182": "Everyday",
		"%183": "Every Monday",
		"%184": "Every Tuesday",
		"%185": "Every Wednesday",
		"%186": "Every Thursday",
		"%187": "Every Friday",
		"%188": "Every Saturday",
		"%189": "Every Sunday",
		"%190": "Current version",
		"%191": "Checking for update...",
		"%192": "You are running the latest version.",
		"%193": "New version is available: V",
		"%194": "Update",
		"%195": "Update in progress, please wait for a few seconds…",
		"%196": "Update in progress, please do not exit. ",
		"%197": "Installing new version...",
		"%198": "Update completed successfully.",
		"%199": "Update failed, please check your network connection.",
		"%200": "You can also download and install the new version from VidOn.me official website at:",
		"%201": "At",
		"%202": "Client Name",
		"%203": "IP Address",
		"%204": "Status",
		"%205": "Currently Playing:",
		"%206": "Sorting rules of media resources",
		"%207": "Setting up this option, you agree to sort media resources per the naming practices of local files.",
		"%208": "Connecting...",
		"%209": "Testing...",
		"%210": "Network abnormal, please retry later!",
		"%211": "Switching media library language...",
		"%212": "Transcoding Settings",
		"%213": "Enable Hardware Transcoding",
		"%214": "Hardware transcoding reduces CPU load to play back videos smoothly.",
		"%215": "Hardware Info",
		"%216": "Your hardware is not optimized for this feature, enabling this option is not recommended",
		"%217": "Graphics Card Chip:",
		"%218": "Hardware Decoding and Encoding:",
		"%219": "Supported",
		"%220": "Not Supported",

		"%228": "Add a Library",
		"%229": "Automatic Categorization",
		"%230": "Home Videos",
		"%231": "Automatically allocate your media sources into corresponding library categories",
		"%232": "Scan movies in the selected directory and collect movie info according to the movie title. DVD and Blu-ray sources can also be analyzed for playback on mobile devices. Other sources that the titles cannot match with any info will be put under “Videos” library",
		"%233": "Collect TV shows info according to the series title and analyze DVD and Blu-ray sources. Only files named in line with “Title-Season-Episode” can be recognized",
		"%234": "Media in “Videos” library are video files in a selected directory, or movies or TV shows that the titles cannot match with any movie or series info",
		"%235": "Scan the photos in the selected directory and add them to “Images” library",
		"%236": "Selected Directory",
		"%237": "Previous",
		"%238": "Next",
		"%239": "Please choose a folder including “movies”, “TV shows”, “videos” or “images”",
		"%240": "Please choose a folder including “movies”",
		"%241": "Please choose a folder including “TV shows”",
		"%242": "Please choose a folder including “videos”",
		"%243": "Please choose a folder including “images”",
		"%244": "Name",
		"%245": "The default name is the last folder name of the selected library path",
		"%246": "VidOn Player",
		"%247": "Download Apps",
		"%248": "Probably the Best Video Player on Mobile Devices",
		"%249": "Local Disk",
		"%250": "Removable Disk",
		"%251": "Network Drive",
		"%252": "Media Backup",
		"%253": "Device Name",
		"%254": "Backup Path",
		"%255": "Backup Date",
		"%256": "Number of Backups",
		"%257": "Set up a home for your scattered photos",
		"%258": "No one will get lost anymore",
		"%259": "VidOn Cloud",
		"%260": "Home Multimedia Center",
		"%261": "To use VidOn Server, make sure you've installed our mobile app on your iOS or Android devices.",
		"%262": "Dear VidOn Player HD users, VidOn Server 0.0.2.1 is ready for use now.",
		"%263": "Click to download VidOn Server 0021",
		"%264": "I've already installed the mobile app.",
		"%265": "Start VidOn Server",
		"%266": "Available soon",
		"%267": "Add Windows Shared/Samba…",
		"%268": "Server Address",
		"%269": "Domain",
		"%270": "Username",
		"%271": "Password",
		"%272": "Server Info",
		"%273": "Server Authorization",
		"%274": "Server location error",
		"%275": "Username or Password error, please try again.",
		"%276": "Access denied",
		"%277": "User name or password not recognized",
		"%278": "Network path not found",
		"%279": "User Center",
		"%280": "VidOn.me account",
		"%281": "Email address",
		"%282": "Expires on",
		"%283": "User information",
		"%284": "Subscribed",
		"%285": "Please use your official VidOn.me account to log in",
		"%286": "Log in",
		"%287": "Register",
		"%288": "Forget password?"
	},
	"en-US": {
		"%title": "American English - l10n.js demo",
		"%info": "You are viewing an American English localization of this page."
	},
	"en-GB": {
		"%title": "British English - l10n.js demo",
		"%info": "You are viewing a British English localisation of this page."
	},
	"en-CA": {
		"%title": "Canadian English - l10n.js demo",
		"%info": "You are viewing a Canadian English localization of this page."
	},
	"en-AU": {
		"%title": "Australian English - l10n.js demo",
		"%info": "You are viewing an Australian English localisation of this page."
	},
	"pt": {
		"%title": "Português - Demo do l10n.js",
		"%info": "Você está vendo uma localiza??o em português desta página.",
		"%101": "Gerenciamento da Biblioteca de Mídia",
		"%102": "Configurações do Servidor",
		"%103": "Trocar de Usuário",
		"%104": "Sair",
		"%105": "Atualizar",
		"%106": "Editar",
		"%107": "Deletar",
		"%108": "Deletar o arquivo de mídia selecionado do servidor?",
		"%109": "Atualiza??o realizada!",
		"%110": "Nome da Mídia",
		"%111": "Tipo de Mídia",
		"%112": "Caminho da Mídia",
		"%113": "Localizar",
		"%114": "Cancelar",
		"%115": "OK",
		"%116": "Status do Servidor",
		"%117": "Geral",
		"%118": "Biblioteca de Mídia",
		"%119": "Transcodifica??o",
		"%120": "Rede",
		"%121": "Informa??es do Servidor",
		"%122": "Nome do Servidor",
		"%123": "Vers?o do Servidor",
		"%124": "IP do Servidor",
		"%125": "Número de Portaria WEB",
		"%126": "Informa??es do Servidor em tempo real",
		"%127": "Cliente em Conex?o Atual",
		"%128": "Uso CPU",
		"%129": "Restante da Memória",
		"%130": "Checar por Atualiza??o",
		"%131": "O nome será aplicado neste servidor de mídia para que os outros computadores da rede possam facilmente identificá-lo. Se você deixar em branco, o sistema usará o nome do computador, por padr?o. ",
		"%132": "Adicionar",
		"%133": "Página de Linguagem WEB",
		"%134": "Iniciar o servi?o nainicializa??o do sistema.",
		"%135": "Salvar",
		"%136": "Caminho do Arquivo Temporário",
		"%137": "Configure um caminho para salvar temporariamente arquivos enquanto transcodifica. O caminho selecionado deverá ter um espa?o livre de pelo menos 1 GB.",
		"%138": "Máximo uso do CPU",
		"%139": "Porta de Streaming de mídia",
		"%140": "Permitir que somente este computador acesse o gerenciamento de página Web.",
		"%141": "Se você definir esta op??o, ent?o, somente os computadores conectados ao servidor VidOn s?o permitidos a acessar http://localhost:32080/ para gerenciamento do servidor.",
		"%142": "Porta Web",
		"%143": "Defina o número de porta de acesso a página de gerenciamento da Web",
		"%144": "Nome de Usuário",
		"%145": "Senha",
		"%146": "O valor padr?o para o nome de usuário e senha é nulo, enquanto entrar na página de gerenciamento de web.",
		"%147": "Biblioteca de mídia auto-atualiza frequentemente",
		"%148": "Nunca",
		"%149": "A cada uma hora",
		"%150": "A cada 12 horas",
		"%151": "Todos os dias",
		"%152": "A cada três dias",
		"%153": "Toda semana",
		"%154": "Todo mês",
		"%155": "Acessando informa??es do filme",
		"%156": "Informa??es salvas com sucesso",
		"%157": "Cancelar informa??es básicas",
		"%158": "Cancelar configura??es de rede",
		"%159": "Atualize todos os recursos de mídia",
		"%160": "Por favor coloque o caminho da mídia corretamente",
		"%161": "Filme",
		"%162": "TV Show",
		"%163": "Vídeo",
		"%164": "Imagem",
		"%165": "Adicionar recursos de mídia",
		"%166": "Editar recursos de mídia",
		"%167": "Automático",
		"%168": "Arquivo de navega??o",
		"%169": "Checar por atualiza??o",
		"%170": "Download Update",
		"%171": "Instalar",
		"%172": "Falha ao baixar, por favor, tente novamente",
		"%173": "A sua vers?o é a mais recente",
		"%174": "A instala??o falhou, por favor, re-instalar",
		"%175": "Download",
		"%176": "Instalar",
		"%177": "Atualizar",
		"%178": "Opções de atualizações",
		"%179": "Automático",
		"%180": "Manual",
		"%181": "Atualizar com frequência:",
		"%182": "Todos os dias",
		"%183": "Toda segunda",
		"%184": "Toda terça",
		"%185": "Toda quarta",
		"%186": "Toda quinta",
		"%187": "Toda sexta",
		"%188": "Todo sábado",
		"%189": "Todo domingo",
		"%190": "Versão atual",
		"%191": "Checando por atualização...",
		"%192": "Você está executando a última versão",
		"%193": "Nova versão está disponível: V",
		"%194": "Atualizar",
		"%195": "Atualização está em progresso, por favor espere por alguns segundos…",
		"%196": "Atualização em progresso, por favor não saia. ",
		"%197": "Instalando nova versão...",
		"%198": "Atualização feita com sucesso.",
		"%199": "Falha na atualização, por favor verifique sua internet.",
		"%200": "Você pode também fazer o download e instalar a nova versão do site oficial VidOn.me em:",
		"%201": "Em",
		"%202": "Client Name",
		"%203": "IP Address",
		"%204": "Status",
		"%205": "Currently Playing:",
		"%206": "Sorting rules of media resources",
		"%207": "Setting up this option, you agree to sort media resources per the naming practices of local files.",

		"%208": "Connecting...",
		"%209": "Testing...",
		"%210": "Network abnormal, please retry later!",
		"%211": "Switching media library language…",
		"%212": "Transcoding Settings",
		"%213": "Enable Hardware Transcoding",
		"%214": "Hardware transcoding reduces CPU load to play back videos smoothly.",
		"%215": "Hardware Info",
		"%216": "Your hardware is not optimized for this feature, enabling this option is not recommended",
		"%217": "Graphics Card Chip:",
		"%218": "Hardware Decoding and Encoding:",
		"%219": "Supported",
		"%220": "Not Supported",

		"%228": "Adicionar a Biblioteca",
		"%229": "Categorização automática",
		"%230": "Home Vídeos",
		"%231": "Automáticamente poner sus recursos multimedias a categorías correspondientes de la biblioteca",
		"%232": "Digitalizar filmes no diretório selecionado e coletar informações do filme de acordo com o título do filme. DVD e Blu-ray fontes também podem ser analisados para reprodução em dispositivos móveis. Outras fontes que os títulos não pode combinar com qualquer informação será colocada em “Videos” biblioteca",
		"%233": "Coletar informações série de TV de acordo com o título da série e analisar em DVD e Blu-ray fontes. Somente os arquivos nomeados de acordo com o “Título-temporada-episódio” pode ser reconhecido",
		"%234": "Mídia em biblioteca “Videos” são arquivos de vídeo em um diretório selecionado, ou filmes ou séries de TV que os títulos não pode combinar com qualquer filme ou série info",
		"%235": "Digitalizar as imagens no diretório selecionado e adicioná-los à biblioteca “Imagens”",
		"%236": "Seleionar um diretório",
		"%237": "Prévio",
		"%238": "Próximo",
		"%239": "Por favor selecione uma pasta incluíndo “filme”, “TV séries”, “videos” ou “imagens”",
		"%240": "Por favor selecione uma pasta incluíndo “filme”",
		"%241": "Por favor selecione uma pasta incluíndo “TV séries”",
		"%242": "Por favor selecione uma pasta incluíndo “videos”",
		"%243": "Por favor selecione uma pasta incluíndo “imagens”",
		"%244": "Nome",
		"%245": "O nome padrão é o ultimo nome usado na pasta na biblioteca",
		"%246": "VidOn Player",
		"%247": "Download Apps",
		"%248": "Probably the Best Video Player on Mobile Devices",
		"%249": "Local Disk",
		"%250": "Removable Disk",
		"%251": "Network Drive",
		"%252": "Media Backup",
		"%253": "Device Name",
		"%254": "Backup Path",
		"%255": "Backup Date",
		"%256": "Number of Backups",
		"%257": "Set up a home for your scattered photos",
		"%258": "No one will get lost anymore",
		"%259": "VidOn Cloud",
		"%260": "Home Multimedia Center",
		"%261": "To use VidOn Server, make sure you've installed our mobile app on your iOS or Android devices.",
		"%262": "Dear VidOn Player HD users, VidOn Server 0.0.2.1 is ready for use now.",
		"%263": "Click to download VidOn Server 0021",
		"%264": "I've already installed the mobile app.",
		"%265": "Start VidOn Server",
		"%266": "Available soon",
		"%267": "Add Windows Shared/Samba…",
		"%268": "Server Address",
		"%269": "Domain",
		"%270": "Username",
		"%271": "Password",
		"%272": "Server Info",
		"%273": "Server Authorization",
		"%274": "Server location error",
		"%275": "Username or Password error, please try again.",
		"%276": "Access denied",
		"%277": "User name or password not recognized",
		"%278": "Network path not found",
		"%279": "User Center",
		"%280": "VidOn.me account",
		"%281": "Email address",
		"%282": "Expires on",
		"%283": "User information",
		"%284": "Subscribed",
		"%285": "Please use your official VidOn.me account to log in",
		"%286": "Log in",
		"%287": "Register",
		"%288": "Forget password?"
	},
	"es": {
		"%title": "Espa?ol - l10n.js demo",
		"%info": "Usted está viendo una versión en espa?ol de esta página.",
		"%101": "Administrar Biblioteca Múltimedia",
		"%102": "Ajustes del Servidor",
		"%103": "Cambiar Usuario",
		"%104": "Salir",
		"%105": "Refrescar",
		"%106": "Editar",
		"%107": "Borrar",
		"%108": "¿ Borrar archivo múltimedia seleccionado desde servidor?",
		"%109": "Refrescar Cumplida!",
		"%110": "Nombre de Media",
		"%111": "Tipo de Media",
		"%112": "Ruta de Media ",
		"%113": "Navegar",
		"%114": "Cancelar",
		"%115": "Aceptar",
		"%116": "Estado del Servidor ",
		"%117": "General",
		"%118": "Biblioteca Múltimedia ",
		"%119": "Transcodificación",
		"%120": "Red",
		"%121": "Información de Servidor",
		"%122": "Nombre de Servidor",
		"%123": "Versión de Servidor ",
		"%124": "IP de Servidor ",
		"%125": "Nombre de Puerto de WEB",
		"%126": "Info de Servidor de Tiempo Real",
		"%127": "Cliente en Conexión Actual",
		"%128": "Uso de CPU ",
		"%129": "Memoria Restante",
		"%130": "Buscar Actualización",
		"%131": "El nombre se aplicará en este servidor de media server por lo que otros ordenadores conectados al internet pueden identificarlo fácilmente. Si lo deja en blanco, el sistema utilizará nombre de tu ordenador por defecto. ",
		"%132": "Añadir",
		"%133": "Idioma de Página WEB",
		"%134": "Iniciar el servicio cuando iniciar el sistema.",
		"%135": "Guardar",
		"%136": "Ruta Temporal de Archivo",
		"%137": "Crear un ruta para guardar archivos temporales cuando transcodificar. La carpeta seleccionada debe tener espacio libre no menos 1GB.",
		"%138": "Uso Máximo de CPU ",
		"%139": "Puerto de streaming media ",
		"%140": "Sólo permitir este ordenador accesar página de Web administración.",
		"%141": "Si elige esta opción, solo los ordenadores conectedos a servidor VidOn está permitido accesar http://localhost:32080/ para administración de servidor.",
		"%142": "Puerto de Web ",
		"%143": "Ajustar número de Puerto accesar de página de administración de Web",
		"%144": "Nombre de Usuario de Administración deWeb",
		"%145": "Contraseña de Administración deWeb ",
		"%146": "El valor por defecto para nombre de usuario y contraseña es nulo al iniciar sesión en la página de administración Web.",
		"%147": "Frecuencia de actualización automática de Biblioteca Múltimedia ",
		"%148": "Nunca",
		"%149": "Cada Hora",
		"%150": "Cada 12 Hora s",
		"%151": "Cada Día",
		"%152": "Cada 3 Días",
		"%153": "Cada Semana",
		"%154": "Cada Mes",
		"%155": "Accesar información de película ",
		"%156": "Información guardada correctamente",
		"%157": "Cancelar información básica ",
		"%158": "Cancelar ajustes de red",
		"%159": "Actualizar todos recursos múltimedia",
		"%160": "Por favor entrar ruta correcta de objetivo media ",
		"%161": "Película",
		"%162": "Series TV",
		"%163": "Vídeo",
		"%164": "Imagen",
		"%165": "Añadir Recurso Múltimedia ",
		"%166": "Editar Recurso Múltimedia ",
		"%167": "Automático",
		"%168": "Escanear archivos",
		"%169": "Verificar actualización",
		"%170": "Descargar actualización",
		"%171": "Instalar",
		"%172": "Fallo en descargar, descargalo de nuevo",
		"%173": "Es la versión más nueva",
		"%174": "Fallo en instalar, instala de nuevo",
		"%175": "Descargando",
		"%176": "Instalando",
		"%177": "Actualizar",
		"%178": "Manera de Actualizar",
		"%179": "Auto",
		"%180": "Manualmente",
		"%181": "Tiempo de Actualizar:",
		"%182": "Cada Día",
		"%183": "Cada Lunes",
		"%184": "Cada Martes",
		"%185": "Cada Miércoles",
		"%186": "Cada Jueves",
		"%187": "Cada Viernes",
		"%188": "Cada Sábado",
		"%189": "Cada Domingo",
		"%190": "Versión Actual",
		"%191": "Verificando Actualización...",
		"%192": "La versión actual es la más nueva.",
		"%193": "Versión nueva encontrada: V",
		"%194": " Actualizar Inmediatamente",
		"%195": "Actualizando, el proceso necesita un poco tiempo, espere por favor... ",
		"%196": "No salga del programa durante la actualización. ",
		"%197": "Instalando versión nueva... ",
		"%198": "Actualizar Correctamente",
		"%199": "Fallo en actualizar, por favor verifique la conexión de red.",
		"%200": "También puede descargar la versión más nueva en VidOn.me, dirección de descarga: ",
		"%201": "En",
		"%202": "Nombre de Cliente",
		"%203": "IP ",
		"%204": "Estado",
		"%205": "Reproduciendo:",
		"%206": "Regla para ordenar recursos en biblioteca múltimedia",
		"%207": "Ajustar esta opción, para ordenar recursos en biblioteca múltimedia según costumbre de nombrar local",

		"%208": "Conectando...",
		"%209": "Verificando...",
		"%210": "Error en red, prueba de nuevo por favor!",
		"%211": "Cambiando el idioma de biblioteca multimedia...",
		"%212": "Ajustes de Transcodificación",
		"%213": "Activar encriptación y desencriptación por hardware",
		"%214": "Activar encriptación y desencriptación por hardware, puede reducir la carga de CPU, y hace la reproducción de vídeo más lisa ",
		"%215": "Info de hardware",
		"%216": "Esta function no está disponible para su hardware, sería major que no active esta function. ",
		"%217": "Chip de tarjeta de vídeo:",
		"%218": "Encriptar y desencriptar por hardware:",
		"%219": "Disponible",
		"%220": "No disponible",

		"%228": "Añadir Biblioteca Multimedia",
		"%229": "Categorizar Automáticamente",
		"%230": "Vídeos",
		"%231": "Automáticamente poner sus recursos multimedias a categorías correspondientes de la biblioteca",
		"%232": "Escanear películas en el directorio seleccionado y colectar info de películas según el título de la película. Recurso de DVD y Blu-ray también se puede analizar para reproducir en dispositivos portátles. Otros recursos que no se ha partido se pondrán en el biblioteca “Videos”",
		"%233": "Recoger info de TV series según el título de la serie y analizar recursos DVD y Blu-ray. Solo archivos nombrado con “Título-Temporada-Episodio” pueden ser reconocidos",
		"%234": "Media en biblioteca “Videos” son archivos video en un directorio seleccionado, o películas o TV series seleccionadas que no se ha partido",
		"%235": "Escanear imágenes en el directorio seleccionado y añadirlas al biblioteca de “Imágenes”",
		"%236": "Directorio Seleccionado",
		"%237": "Previo",
		"%238": "Próximo",
		"%239": "Por favor elija una carpeta incluyendo “películas”, “TV series”, “videos” o “imágenes”",
		"%240": "Por favor elija una carpeta incluyendo “películas”",
		"%241": "Por favor elija una carpeta incluyendo “TV series”",
		"%242": "Por favor elija una carpeta incluyendo “videos”",
		"%243": "Por favor elija una carpeta incluyendo “imágenes”",
		"%244": "Nombre",
		"%245": "El nombre por defecto es lo de la carpeta de última nivel de la ruta del biblioteca seleccionado",
		"%246": "VidOn Player",
		"%247": "Descargue Apps",
		"%248": "Posible el Mejor Reproductor de Vídeo en Dispositivos Portables",
		"%249": "Disco Local",
		"%250": "Disco Externo",
		"%251": "Unidad de Red",
		"%252": "Hacer copia de seguridad de recurso multimedia",
		"%253": "Nombre de Dispositivo",
		"%254": "Ruta de copia de seguridad",
		"%255": "Fecha de copia de seguridad",
		"%256": "Cantidad de copia de seguridad",
		"%257": "Preparar un cobertizo para sus fotos dispersas",
		"%258": "Nunca se preocupará por perderlas",
		"%259": "VidOn Cloud",
		"%260": "Centro de Administración de Media de Familia",
		"%261": "VidOn Server funciona junto con las aplicaciones en dispositivo portable",
		"%262": "Los usuarios de VidOn Player HD, por favor use la versión 0.0.2.1 de VidOn Server",
		"%263": "Pinche para descargar VidOn Server 0021",
		"%264": "He instalado la aplicación en dispositivo portable",
		"%265": "Empieza a usar",
		"%266": "Available soon",
		"%267": "Añadir Recursos Compartidos/Samba...",
		"%268": "Dirección del Servidor",
		"%269": "Dominio",
		"%270": "Nombre de usuario",
		"%271": "Contraseña",
		"%272": "Información del Servidor",
		"%273": "Verificar el Servidor",
		"%274": "Error en Dirección del Servidor",
		"%275": "¡Por favor verifique el nombre de usuario y la contraseña!",
		"%276": "Se rechazó la visita",
		"%277": "Nombre de Usuario o contraseña incorrectos",
		"%278": "No se encontró la ruta de red",
		"%279": "Centro de Usuario",
		"%280": "Cuenta de VidOn.me",
		"%281": "Dirrección de correo",
		"%282": "Licencia de Membresía",
		"%283": "Información de usuario",
		"%284": "Ha suscrito",
		"%285": "Por favor iniciesesión con la cuenta de VidOn.me que ha registradoen el sitio web oficial",
		"%286": "IniciarSesión",
		"%287": "Registrar Gratis",
		"%288": "¿Se olvidó de su contraseña?"
	},
	"fr": {
		"%title": "Fran?ais - Démo de l10n.js",
		"%info": "Vous lisez une localisation en fran?ais de cette page.",
		"%101": "Gestionnaire des médiathèque ",
		"%102": "Paramètres du serveur",
		"%103": "Changer d'utilisateur",
		"%104": "Déconnexion",
		"%105": "Actualiser",
		"%106": "Editer",
		"%107": "Supprimer",
		"%108": "Supprimez le fichier multimédia à partir du serveur?",
		"%109": "Actualisez avec succès!",
		"%110": "Nom du média",
		"%111": "Type de média ",
		"%112": "Chemin de média",
		"%113": "Parcourir",
		"%114": "Annuler",
		"%115": "OK",
		"%116": "Etat du serveur",
		"%117": "Général",
		"%118": "Mediathèque",
		"%119": "Transcode",
		"%120": "Réseau",
		"%121": "Information du serveur",
		"%122": "Nom du serveur",
		"%123": "Version du serveur",
		"%124": "IP du serveur",
		"%125": "Numéro de port WEB",
		"%126": "Info du serveur en temps réel",
		"%127": "Client connecté actuellement",
		"%128": "Utilisation du processeur",
		"%129": "Mémoire disponible",
		"%130": "Vérifiez la mise à jour",
		"%131": "Le nom sera appliqué sur ce serveur multimédia afin que d'autres ordinateurs puissent facilement l'identifier. Si vous laissez le champ vide, le système va utiliser votre nom de l'ordinateur par défaut.",
		"%132": "Ajouter",
		"%133": "Langue de Page WEB",
		"%134": "Démarrer le service au démarrage du sytème.",
		"%135": "Enregistrer",
		"%136": "Chemin du fichier temporaire",
		"%137": "Configurez un chemin pour enregistrer les fichiers temporaires lors du transcode. La parition sélectionnée doit avoir un espace libre d'au moins 1 Go.",
		"%138": "Utilisation du processeur maximum",
		"%139": "Streaming media port",
		"%140": "Autoriser uniquement cet ordinateur à accéder à la page de gestion web.",
		"%141": "Si vous activez cette option,seuls les ordinateurs connectés au serveur VidOn sont autorisés à accéder à http://localhost:32080/ pour la gestion du serveur.",
		"%142": "Web Port",
		"%143": "Configurez le numéro de port pour accéder à la page de gestion WEB",
		"%144": " Nom d'utilisateur de gestion Web",
		"%145": " Mot de passe de gestion Web",
		"%146": "Le nom d'utilisateur et le mot de passe sont nuls par défaut lors de la connexion dans la page de gestion Web.",
		"%147": " Fréquence de mise à jour de médiathèque automique",
		"%148": "Jamais",
		"%149": "Toutes les heures",
		"%150": "Toutes les 12 heures",
		"%151": "Tous les jours",
		"%152": "Tous les trois jours",
		"%153": "chaque semaine",
		"%154": "chaque mois",
		"%155": "Accès aux informations du film",
		"%156": "Information enregistrée avec succès",
		"%157": "Annuler les informations de base",
		"%158": "Annuler les réglages de réseau",
		"%159": "Mettre à jour toutes les ressources des médias",
		"%160": "Veuillez entrer le chemin de média cible correctement",
		"%161": "Film",
		"%162": "Feuilleton",
		"%163": "Vidéo",
		"%164": "Image",
		"%165": "Ajouter une média source",
		"%166": "Editer le média source",
		"%167": "Automatique",
		"%168": "Parcourir les fichiers",
		"%169": "Vérifier la mise à jour",
		"%170": "Télécharger la mise à jour",
		"%171": "Installer",
		"%172": "Téléchargement échoué, veuillez re-télécharger",
		"%173": "La version actuelle est la dernière",
		"%174": "Installation échouée, veuillez réinstaller",
		"%175": "Téléchargement",
		"%176": "Installation",
		"%177": "Mise à jour",
		"%178": "Mode de mise à jour",
		"%179": "Auto",
		"%180": "Manuel",
		"%181": "Le temps de mise à jour:",
		"%182": "Tous les jours",
		"%183": "Tous les lundis",
		"%184": "Tous les mardis",
		"%185": "Tous les mercredis",
		"%186": "Tous les jeudis",
		"%187": "Tous les vendredis",
		"%188": "Tous les samedis",
		"%189": "Tous les dimanches",
		"%190": "Version actuelle",
		"%191": "Vérification de mise à jour…",
		"%192": "La version actuelle est déjà la dernière",
		"%193": "La nouvelle version est disponible: V",
		"%194": "Mettre à jour maintennat",
		"%195": "La mise à jour prendra une peu de temps, veuillez patienter…",
		"%196": "Ne quittez pas l'application pendant le processus de mise à jour",
		"%197": "Installation de la nouvelle version…",
		"%198": "Mise à jour avec réussie ",
		"%199": "Mise à jour échouée, vérifiez la connexion Internet.",
		"%200": "Vous pouvez aller au site officiel de VidOn.me pour télécharger la mise à jour, l'adresse de téélchargement:",
		"%201": "à",
		"%202": "Nom du client",
		"%203": "Adresse IP",
		"%204": "État",
		"%205": "En lecture:",
		"%206": "Règle de mettre en ordre les ressources de médiathèque",
		"%207": "Cette option permet de mettre en ordre les ressources de médiathèque selon la convention de dénomination des fichiers locale",

		"%208": "En connexion… ",
		"%209": "Vérification en cours…",
		"%210": "Réseau anormal, veuillez réessayer plus tard !",
		"%211": "Commutation de langue de médiathèque…",
		"%212": "Paramètres de transcode",
		"%213": "Activer le décodage matéril et le codage matéril ",
		"%214": "Activer le décodage matériel et le codage matériel pour réduire la charge du CPU, et render la lecture de vidéo plus fluide",
		"%215": "Info de matériel",
		"%216": "Vous n'êtes pas commandé d'activer cette fonctionnalité, car votre appareil matériel ne peut pas bien la supporter.",
		"%217": "Puce graphique:",
		"%218": "Décodage matériel et codage matériel:",
		"%219": "supporté",
		"%220": "non supporté",

		"%228": "Ajouter une médiathèque",
		"%229": "Classification automatique",
		"%230": "Vidéo de famille",
		"%231": "Classer la ressource média automatiquement à la médiathèque appropriée",
		"%232": "Scanner les films sous le répertoire de fichier sélectionné et obtenir les infos précises selon le nom du film. Analyser les sources DVD et Blu-ray et les lire dans le terminal mobile. Les ressources non correspondantes seront mises dans la médiathèque « vidéo de famille »",
		"%233": "Obtenir les infos du film selon le nom de séries et analyser les sources DVD et Blu-ray. Pour être connu, il faut nommer le fichier au règle « Nom – Saison – épisode »",
		"%234": "Les fichiers vidéo sous répertoire sélectionné, les films non correspondants selon le nom, et les ressources séries TV sont tous ajoutés à la médiathèque « vidéo de famille »",
		"%235": "Scanner les images dans le dossier sélectionné et les ajouter dans la médiathèque",
		"%236": "Répertoire sélectionné",
		"%237": "Précédent",
		"%238": "Suivant",
		"%239": "Sélectionner les dossiers incluant « film », « Séries TV », « vidéo » et « image »",
		"%240": "Sélectionner le dossier incluant « film »",
		"%241": "Sélectionner le dossier incluant « Séries TV »",
		"%242": "Sélectionner le dossier incluant « vidéo »",
		"%243": "Sélectionner le dossier incluant « image »",
		"%244": "Nom",
		"%245": "Le nom par défaut est celui du dernier dossier du répertoire de médiathèque sélectionné",
		"%246": "VidOn Player",
		"%247": "Télécharger Apps",
		"%248": "Probablement le meilleur lecteur vidéo sur les appareils mobiles",
		"%249": "Disque local",
		"%250": "Disque amovible",
		"%251": "Pilote réseau",
		"%252": "Sauvegarde de média",
		"%253": "Nom de l'appareil",
		"%254": "Répertoire de sauvegarde",
		"%255": "Date de sauvegarde",
		"%256": "Nombre de sauvegardes",
		"%257": "Établissez une maison pour vos photos éparpillées",
		"%258": "Aucun souci à perdre désormais",
		"%259": "VidOn Cloud",
		"%260": "Centre multimédia à domicile",
		"%261": "Pour utiliser les fonctionnalités de VidOn Server, il faut fonctionner avec l'application mobile.",
		"%262": "Pour les utilisateurs de VidOn Player HD, il faut utiliser d'abord la version 0.0.2.1 de VidOn Server.",
		"%263": "Cliquer pour télécharger VidOn Server 0021",
		"%264": "L'application mobile a été installée",
		"%265": "Démarrer",
		"%266": "Available soon",
		"%267": "Ajouter le serveur Windows Shared/Samba...",
		"%268": "Adresse de serveur",
		"%269": "Domaine",
		"%270": "Nom d’utilisateur",
		"%271": "Mot de passe",
		"%272": "Info de serveur",
		"%273": "Authentification de serveur",
		"%274": "Adresse de serveur est incorrecte",
		"%275": "Veuillez vérifier si le nom d’utilisateur et le mot de passe sont corrects!",
		"%276": "L'accès est refusé",
		"%277": "Nom d'utilisateur ou mot de passe est incorrect",
		"%278": "Chemin de réseau non trouvé",
		"%279": "Centre utilisateur",
		"%280": "Compte VidOn.me",
		"%281": "Adresse d'email",
		"%282": "Expirer à",
		"%283": "Info d'utilisation",
		"%284": "Abonné",
		"%285": "Veuillez utiliser le compte VidOn.me créé sur le site officiel",
		"%286": "Connexion",
		"%287": "S’inscrire",
		"%288": "Mot de passe oublié?"
	},
	"nl": {
		"%title": "Nederlands - Demo van l10n.js",
		"%info": "U ziet nu een Nederlandse lokalisatie van deze pagina."
	},
	"de": {
		"%title": "Deutsch - l10n.js Demo",
		"%info": "Sie sehen hier die deutsche Lokalisierung dieser Seite.",
		"%101": "Medienbibliothek verwalten",
		"%102": "Server-Einstellungen",
		"%103": "Benutzer wechseln",
		"%104": "Abmelden",
		"%105": "Aktualisieren",
		"%106": "Bearbeiten",
		"%107": "Löschen",
		"%108": "Möchten Sie die ausgewählte Mediadatei vom Server löschen?",
		"%109": "Aktualisierung erfolgreich!",
		"%110": "Titel",
		"%111": "Medientyp",
		"%112": "Speicherort",
		"%113": "Durchsuchen",
		"%114": "Abbrechen",
		"%115": "OK",
		"%116": "Serverstatus",
		"%117": "Allgemein",
		"%118": "Medienbibliothek",
		"%119": "Umkodierung",
		"%120": "Netzwerk",
		"%121": "Server-Info",
		"%122": "Servername",
		"%123": "Serverversion",
		"%124": "Server-IP",
		"%125": "WEB Port-Nummer",
		"%126": "Server-Echtzeit-Informationen",
		"%127": "Aktuell verbundene Clients",
		"%128": "CPU-Auslastung",
		"%129": "Freier Speicher",
		"%130": "Nach Updates suchen",
		"%131": "Dieser Name wird zum Identifizieren des Mediaservers im Neztwerk verwendet. Wenn Sie hier leer bleiben, wird Ihr Computername dafür verwendet.",
		"%132": "Hinzufügen",
		"%133": "WEB Anzeigesprache",
		"%134": "Autostart",
		"%135": "Speichern",
		"%136": "Speicherort der tempor?ren Dateien",
		"%137": "Stellen Sie den Speicherort der temporätren Dateien bei der Umkodierung ein. Es wird empfohlen, dass die ausgewählte Festplatte über mindestens 1GB freien Speicherplatz verfügt",
		"%138": "Maximale CPU-Auslastung",
		"%139": "Steaming-Port",
		"%140": "Nur diesen Computer den Zugriff auf die Web-Verwaltungsseite gestatten",
		"%141": "Wenn Sie diese Option aktivieren, darf nur der Computer, auf dem der VidOn Server installiert wurde, durch http://localhost:32080/ den Server verwalten.",
		"%142": "Web-Port",
		"%143": "Port zur Web-Verwaltungsseite einstellen",
		"%144": "Login Benutzername",
		"%145": "Login Passwort",
		"%146": "Der Standard-Benutzername und das Standard-Passwort ist leer",
		"%147": "Die Medienbibliothek automatisch aktualisieren",
		"%148": "Nie",
		"%149": "Jede Stunde",
		"%150": "Jede 12 Stunden",
		"%151": "Täglich",
		"%152": "Jede 3 Tage",
		"%153": "Wöchentlich",
		"%154": "Jeden Monat",
		"%155": "Film-Informationen abrufen",
		"%156": "Informationen gespeichert",
		"%157": "Speichern der Basic-Informationen abbrechen",
		"%158": "Netzwerk-Einstellungen abbrechen",
		"%159": "Alle Ressourcen aktualisieren",
		"%160": "Bitte geben Sie den richtigen Pfad der Mediadatei ein",
		"%161": "Filme",
		"%162": "TV-Serien",
		"%163": "Videos",
		"%164": "Bilder",
		"%165": "Mediadatei hinzufügen",
		"%166": "Mediadatei bearbeiten",
		"%167": "Automatisch",
		"%168": "Dateien durchsuchen",
		"%169": "Nach Updates suchen",
		"%170": "Updates herunterladen",
		"%171": "Installieren",
		"%172": "Download fehlgeschlagen, bitte versuchen Sie es erneut.",
		"%173": "Sie haben die neueste Version.",
		"%174": "Installation fehlgeschlagen, bitte versuchen Sie es erneut.",
		"%175": "Wird heruntergeladen",
		"%176": "Wird installiert",
		"%177": "Aktualisieren",
		"%178": "Wie werden Updates installiert",
		"%179": "Automatisch",
		"%180": "Manuell",
		"%181": "Neue Updates installieren:",
		"%182": "Täglich",
		"%183": "Jeden Montag",
		"%184": "Jeden Dienstag",
		"%185": "Jeden Mittwoch",
		"%186": "Jeden Donnerstag",
		"%187": "Jeden Freitag",
		"%188": "Jeden Samstag",
		"%189": "Jeden Sonntag",
		"%190": "Aktuelle Version",
		"%191": "Nach Updates suchen...",
		"%192": "Sie haben bereits die neueste Version.",
		"%193": "Eine neue Version ist verfügbar: V",
		"%194": "Jetzt aktualisieren",
		"%195": "Die Aktualisierung kann einige Zeit dauern, bitte warten...",
		"%196": "Während des Updatevorgangs schließen Sie bitte das Programm nicht.",
		"%197": "Update installieren...",
		"%198": "Update erfolgreich installiert",
		"%199": "Aktualisieren fehlgeschlagen, bitte überprüfen Sie Ihre Netzwerkeinstellungen. ",
		"%200": "Sie können Updates auch auf der offiziellen Seite von VidOn.me herunterladen:",
		"%201": "um",
		"%202": "Servername",
		"%203": "IP-Adresse",
		"%204": "Status",
		"%205": "Wiedergabe:",
		"%206": "Sortierungsregel der Medienbibliothek",
		"%207": "Sollten Sie diese Option einstellen, werden die Mediendateien nach lokalen Dateinamenskonventionen sortiert ",

		"%208": "Verbinde...",
		"%209": "Überprüfe...",
		"%210": "Netzwerk nicht verfügbar, bitte versuchen Sie es später erneut. ",
		"%211": "Sprache der Medienbibliothek wird gewechselt...",
		"%212": "Codierungseinstellungen",
		"%213": "Hardware-Codierung/-Decodierung aktivieren ",
		"%214": "Hardware-Codierung/-Decodierung-Funktion kann CPU-Auslastung verringern und Video-Wiedergabe flüssiger machen",
		"%215": "Hardware-Informationen",
		"%216": "Ihre Hardware unterstützt diese Funktion nicht sehr gut. Es wäre besser, dass Sie diese Funktion nicht aktivieren.",
		"%217": "Grafikchip:",
		"%218": "Hardware-Codierung/-Decodierung: ",
		"%219": "Unterstützt",
		"%220": "Nicht Unterstützt",

		"%228": "Medienbibliothek hinzufügen",
		"%229": "Automatische Kategorisierung",
		"%230": "Videos",
		"%231": "Ihre Medienressouren werden automatisch den entsprechenden Bibliotheken zugeordnet",
		"%232": "Scannt Filme im ausgewählten Verzeichnis und sammelt Filminformationen nach dem Filmtitel. DVD und Blu-ray-Quellen werden auch für die Wiedergabe auf mobilen Geräten analysiert. Andere Ressourcen, die nicht entsprechend kategorisiert werden können, werden der „Videos“-Bibliothek zugeordnet",
		"%233": "Sammelt Details der TV-Serien online gemäß dem Titel. DVD-und Blu-ray-Quellen werden auch analysiert. Nur Dateien, die mit der Namensregeln „Titel-Staffel-Episode“ bezeichnet werden, können erkannt und dieser Bibliothek zugeordnet werden",
		"%234": "Videodateien, die nicht in der „Filme“-oder „TV-Serien“-Bibliothek kategorisiert wurden, werden zur Videos-Bibliothek hinzugefügt",
		"%235": "Scannt Bilder im ausgewählten Verzeichnis und fügt sie zur „Bilder“-Bibliothek hinzu",
		"%236": "Ausgewähltes Verzeichnis",
		"%237": "Zurück",
		"%238": "Weiter",
		"%239": "Bitte wählen Sie einen Ordner einschließlich  „Filme“, „TV-Serien“, „Videos“ oder „Bilder“",
		"%240": "Bitte wählen Sie einen Ordner einschließlich „Filme“ aus",
		"%241": "Bitte wählen Sie einen Ordner einschließlich „TV-Serien“ aus",
		"%242": "Bitte wählen Sie einen Ordner einschließlich „Videos“ aus",
		"%243": "Bitte wählen Sie einen Ordner einschließlich „Bilder“ aus",
		"%244": "Name",
		"%245": "Der Standardname ist der Name des letzten Unterordners im ausgewählten Bibliothekspfad",
		"%246": "VidOn Player",
		"%247": "Apps herunterladen",
		"%248": "Wahrscheinlich der beste Video Player für mobile Geräte",
		"%249": "Lokaler Datenträger",
		"%250": "Wechseldatenträger",
		"%251": "Netzlaufwerk",
		"%252": "Medien Backup",
		"%253": "Gerätename",
		"%254": "Backup Pfad",
		"%255": "Backup Datum",
		"%256": "Anzahl der Backups",
		"%257": "Erstellen Sie ein zu hause für Ihre zerstreuten Fotos.",
		"%258": "Keines wird mehr verloren gehen.",
		"%259": "VidOn Cloud",
		"%260": "Home Multimedia Center",
		"%261": "VidOn Server muss mit derApp auf dem Mobilgerät zusammen arbeiten",
		"%262": "Benutzer des VidOn Player HD, bitte nutzen Sie die Version 0.0.2.1 von VidOn Server",
		"%263": "Klickenzum Download von VidOn Server 0021",
		"%264": "Ich habe die App auf dem Mobilgerät installiert",
		"%265": "Jetzt starten",
		"%266": "Available soon",
		"%267": "Windows Shared/Samba...hinzufügen",
		"%268": "Serveradresse",
		"%269": "Domain",
		"%270": "Benutzername",
		"%271": "Passwort",
		"%272": "Serverinfo",
		"%273": "Serverauthentifizierung",
		"%274": "Falsche Serveradresse",
		"%275": "Bitte überprüfen Sie ob Ihr Benutzername oder Passwort korrekt ist.",
		"%276": "Der Zugriff wurde verweigert",
		"%277": "Der Benutzername oder das Passwort ist falsch",
		"%278": "Der Netzwerkpfad wurde nicht gefunden",
		"%279": "Benutzerzentrum",
		"%280": "VidOn.me Account",
		"%281": "E-Mail",
		"%282": "Gültigkeitsdauer",
		"%283": "Benutzerinformation",
		"%284": "Abonniert",
		"%285": "BittemeldenSiesichmitIhrem VidOn.me Account an",
		"%286": "Anmelden",
		"%287": "Registrieren",
		"%288": "Passwort vergessen?"
	},
	"fi": {
		"%title": "Suomen kieli - l10n.js demo",
		"%info": "Katselet Suomeksi k??nnetty? versiota t?st? sivusta"
	},
	"vi": {
		"%title": "Ti?ng Vi?t - l10n.js demo",
		"%info": "B?n ?ang xem trang b?ng phiên b?n ti?ng Vi?t."
	},
	"it": {
		"%title": "Italiano - Demo di l10n.js",
		"%info": "Stai leggendo una localizzazione in Italiano di questa pagina."
	},
	"no": {
		"%title": "Norsk - Demo av l10n.js",
		"%info": "Du ser den norske oversettelsen av denne siden."
	},
	"ru": {
		"%title": "Русский - l10n.js демо",
		"%info": "Вы просматриваете Русскую версию этой страницы."
	},
	"jbo": {
		"%title": "la'o cme. l10n.js .cme mupli bau le jbobau",
		"%info": ".i do ca viska lo jbobau xe fanva be lo ti judrysni"
	},
	"da": {
		"%title": "Dansk. Demo af l10n.js",
		"%info": "Du ser den Danske overs?ttelse af denne side"
	},
	"he": {
		"%locale.dir": "rtl",
		"%title": "????? - Demo do l10n.js",
		"%info": "??? ???? ?????????? ?????? ?? ???? ??."
	},
	"bg": {
		"%title": "Български - демо на l10n.js",
		"%info": "В момента виждате българската версия на тази страница."
	},
	"ko": {
		"%101": "미디어 라이브러리 관리",
		"%102": "서버 설정",
		"%103": "사용자 전환",
		"%104": "로그 아웃",
		"%105": "새로 고침",
		"%106": "편집",
		"%107": "삭제",
		"%108": "서버에서 선택된 미디어 파일을 삭제하시겠습니까?",
		"%109": "새로 고쳐졌습니다!",
		"%110": " 미디어 이름",
		"%111": " 미디어 유형",
		"%112": "미디어 경로",
		"%113": "찾아보기",
		"%114": "취소",
		"%115": "확인",
		"%116": "서버 상태",
		"%117": "일반",
		"%118": "미디어 라이브러리",
		"%119": "트랜스코딩",
		"%120": "네트워크",
		"%121": "서버 정보",
		"%122": "서버 이름",
		"%123": "서버 버전",
		"%124": "서버 IP",
		"%125": "WEB 포트 번호",
		"%126": "실시간 서버 정보",
		"%127": "현재 연결된 클라이언트",
		"%128": "CPU 사용률",
		"%129": "잔류 메모리",
		"%130": "업데이트 체크",
		"%131": "이름이 이 미디어 서버에 적용됨으로 다른 네트워크 컴퓨터에 쉽게 실별될 수 있습니다. 비워두시면 시스템은 컴퓨터 이름을 기본으로 설정합니다.",
		"%132": "추가",
		"%133": "WEB 페이지 언어",
		"%134": "시스템 기동시 서비스 시작",
		"%135": "저장",
		"%136": "임시 파일 경로",
		"%137": "트랜스 코딩시 임시 파일을 저장하는 경로를 설정합니다. 선택한 파티션은 1GB이상의 여유 공간이 있어야 합니다.",
		"%138": " 최대 CPU 사용률",
		"%139": "스트리밍 미디어 포트",
		"%140": "이 컴퓨터만 Web 관리 페이지를 액세스 가능하도록 합니다.",
		"%141": "이 옵션을 활성화시키면 VidOn Server가 설치된 컴퓨터에서만 http://localhost:32080/을 액세스하고 관리 가능합니다.",
		"%142": "웹 포트",
		"%143": "웹 관리 페이지의 액세스 포트 번호 설정",
		"%144": "웹 관리 사용자 이름",
		"%145": "웹 관리 비밀 번호",
		"%146": "웹 관리 페이지에 로그인시 기본 사용자 이름과 비밀 번호는 공백입니다.",
		"%147": "미디어 라이브러리 자동 업데이트 빈도",
		"%148": "하지 않기",
		"%149": "매시간",
		"%150": "매12시간",
		"%151": "매일",
		"%152": "매3일간",
		"%153": "매주",
		"%154": "매달",
		"%155": "영화 정보 보기",
		"%156": "정보가 저장되었습니다",
		"%157": "기본 정보 취소",
		"%158": "네트워크 설정 취소",
		"%159": "모든 미디어 자원 업데이트",
		"%160": "정확한 타깃 미디어 경로를 입력해 주십시오",
		"%161": "영화",
		"%162": "TV 쇼",
		"%163": "동영상",
		"%164": "이미지",
		"%165": "미디어 자원 추가",
		"%166": "미디어 자원 편집",
		"%167": "자동",
		"%168": "파일 보기",
		"%169": "업데이트 체크",
		"%170": "업데이트 다운로드",
		"%171": "설치",
		"%172": "다운로드 실패, 다시 다운로드하기",
		"%173": "이미 최신버전입니다.",
		"%174": "설치 실패, 다시 설치하기",
		"%175": "다운로드중",
		"%176": "설치중",
		"%177": "업데이트",
		"%178": "업데이트 방식",
		"%179": "자동",
		"%180": "수동",
		"%181": "업데이트 시간:",
		"%182": "매일",
		"%183": "매주 월요일",
		"%184": "매주 화요일",
		"%185": "매주 수요일",
		"%186": "매주 목요일",
		"%187": "매주 금요일",
		"%188": "매주 토요일",
		"%189": "매주 일요일",
		"%190": "사용중인 버전",
		"%191": "새 업데이트 체크중...",
		"%192": "사용중인 버전이 최신 버전입니다",
		"%193": "새 버전을 발견했습니다: V",
		"%194": "즉시 업데이트",
		"%195": "업데이트중 입니다, 잠시만 기다려 주십시오…",
		"%196": "업데이트중 응용 프로그램을 종료시켜 주시지 마십시오.",
		"%197": "새 버전 설치중...",
		"%198": "업데이트 성공되었습니다",
		"%199": "업데이트가 실패되었습니다. 네트워크 연결을 확인해 보십시오.",
		"%200": "VidOn.me 공식 사이트에서 업데이트 프로그램을 다운로드하실 수 있습니다. 다운로드 주소:",
		"%201": "다음 주소에서 다운로드 가능합니다",
		"%202": "클라이언트 이름",
		"%203": "IP 주소",
		"%204": "상태",
		"%205": "재생중인 영화:",
		"%206": "미디어 라이브러리 자원 정렬 방식",
		"%207": "이 옵션을 설정하면 로컬 파일 이름의 규칙에 따라 미디어 자원을 배렬시킵니다",

		"%208": "연결중...",
		"%209": "검출중...",
		"%210": "네트워크 오류가 발생되었습니다. 잠시후 다시 시도해 보십시오!",
		"%211": "미디어 라이브러리 언어를 전환하는 중 입니다…",
		"%212": "트랜스 코딩 설정",
		"%213": "하드웨어 디코딩 열기",
		"%214": "하드웨어 디코딩 기능을 열면 CPU 사용량을 줄일 수 있음으로 동영상을 더욱 유연히 재생할 수 있습니다",
		"%215": "하드웨어 정보",
		"%216": "하드웨어 장치가 이 기능을 완벽히 지원하지 않습니다. 이 기능을 실행하지 않는 것이 좋습니다.",
		"%217": "그래픽 칩:",
		"%218": "하드웨어 디코딩 하드웨어 인코딩:",
		"%219": "지원",
		"%220": "지원되지 않음",

		"%228": "미디어 추가",
		"%229": "자동 분류",
		"%230": "홈 동영상",
		"%231": "자동적으로 미디어 소스를 상응한 미디어 라이브러리에 추가하기",
		"%232": "모든 디렉토리중의 영화를 스캔하고 영화 이름에 따라 영화 상세정보를 획득합니다. 동시에 블루레이, DVD 소스를 분석하고 모바일 장치에서 재생할 수 있습니다. 일치화되지 못한 소스는 “홈 동영상” 라이브러리로 저장됩니다",
		"%233": "드라마 이름에 따라 상세정보를 획득하고 블루레이, DVD 소스를 분석할 수 있습니다. 이름 격식이 “이름-회수-에피소드 번호”로 된 파일만이 식별됩니다",
		"%234": "선택된 파일 디렉토리중 동영상 파일 혹은 이름에 따라 인식되지 못한 영화, 드라마 자원은 모드 “홈 자원” 라이브러리로 저장됩니다",
		"%235": "모든 폴더에 포함된 이미지를 스캔하고 이미지 라이브러리 자원으로 저장됩니다",
		"%236": "선택된 디렉토리",
		"%237": "이전",
		"%238": "다음",
		"%239": "“영화”, “드라마”, “동영상”, “이미지” 자원이 포함된 폴더 선택하기",
		"%240": "“영화” 자원이 포함된 폴더 선택하기",
		"%241": "“드라마” 자원이 포함된 폴더 선택하기",
		"%242": "“동영상” 자원이 포함된 폴더 선택하기",
		"%243": "“이미지” 자원이 포함된 폴더 선택하기",
		"%244": "이름",
		"%245": "선택된 라이브러리 경로의 최종 폴더 이름을 기본 이름으로 설정합니다",
		"%246": "VidOn Player",
		"%247": "다운로드 Apps",
		"%248": "최고의 모바일 장치용 동영상 플레이어",
		"%249": "로컬 디스크",
		"%250": "이동식 디스크",
		"%251": "네트워크 드라이버",
		"%252": "미디어 백업",
		"%253": "장치 이름",
		"%254": "백업 경로",
		"%255": "백업 시간",
		"%256": "백업 수량",
		"%257": "흩어져 사진을 설정 홈",
		"%258": "당신은 편리하게 관리 할 수 있습니다",
		"%259": "VidOn Cloud",
		"%260": "홈 멀티 미디어 관리 센터",
		"%261": "VidOn Server의 각 기능은 모바일 응용 프로그램과 함께 실행해야 사용 가능합니다.",
		"%262": "VidOn Media Player HD 사용자분, VidOn Server 0.0.2.1 버전을 사용해 주십시오.",
		"%263": "클릭하고 VidOn Server 0021 다운로드",
		"%264": "이미 모바일 앱을 설치했음",
		"%265": "실행하기",
		"%266": "Available soon",
		"%267": "Windows Shared/Samba 추가...",
		"%268": "서버 주소",
		"%269": "도메인",
		"%270": "아이디",
		"%271": "비밀 번호",
		"%272": "서버 정보",
		"%273": "서버 인증",
		"%274": "서버 주소가 잘못되었습니다",
		"%275": "아이디와 비밀번호가 정확한지 체크해 보십시오!",
		"%276": "방문하는데 실패되었습니다",
		"%277": "아이디 혹은 비밀번호가 잘못되었습니다",
		"%278": "네트워크 경로를 찾지 못했습니다",
		"%279": "사용자센터",
		"%280": "VidOn.me계정",
		"%281": "이메일주소",
		"%282": "회원유효기간",
		"%283": "사용자정보",
		"%284": "이미구독했습니다",
		"%285": "공식웹사이트에서등록한 VidOn.me 계정으로등록해주십시오",
		"%286": "로그인",
		"%287": "등록",
		"%288": "비밀번호 되찾기?"
	},
	"zh-cn": {
		"%101": "媒体库管理",
		"%102": "服务器设置",
		"%103": "切换账户",
		"%104": "注销",
		"%105": "刷新",
		"%106": "编辑",
		"%107": "删除",
		"%108": "确定从服务器中删除此媒体源？",
		"%109": "刷新成功！",
		"%110": "媒体源名称",
		"%111": "媒体源类型",
		"%112": "媒体源路径",
		"%113": "浏览",
		"%114": "取消",
		"%115": "确定",
		"%116": "服务器状态",
		"%117": "通用",
		"%118": "媒体库",
		"%119": "转码",
		"%120": "网络",
		"%121": "服务器基本信息",
		"%122": "服务器名称",
		"%123": "服务器版本",
		"%124": "服务器IP",
		"%125": "WEB端口号",
		"%126": "服务器实时信息",
		"%127": "当前连接客户端",
		"%128": "CPU使用率",
		"%129": "剩余内存",
		"%130": "检查更新",
		"%131": "这个名称将被使用于此媒体服务器以便你网络上的其他电脑可以辨认它，如果你留空白，会默认使用你的电脑名称。",
		"%132": "添加",
		"%133": "WEB页面语言",
		"%134": "开机自动启动服务",
		"%135": "保存",
		"%136": "临时文件路径",
		"%137": "设置你的服务器在转码时存储临时文件的路径。建议所选分区剩余空间大于1GB",
		"%138": "CPU最大使用率",
		"%139": "流媒体端口",
		"%140": "只允许本机访问Web管理页面",
		"%141": "设置此选项，则只允许威动服务器所安装的机器访问链接 http://localhost:32080/来管理服务器",
		"%142": "Web端口",
		"%143": "设置Web管理页面的访问端口号",
		"%144": "Web管理登陆用户名",
		"%145": "Web管理登陆密码",
		"%146": "登陆Web管理页面时用户名和密码，默认为空",
		"%147": "自动更新媒体库时间间隔",
		"%148": "从不更新",
		"%149": "1小时",
		"%150": "12小时",
		"%151": "每天",
		"%152": "3天",
		"%153": "一周",
		"%154": "一个月",
		"%155": "获取电影信息语言",
		"%156": "保存信息成功",
		"%157": "取消基本信息",
		"%158": "取消网络设置",
		"%159": "更新全部源",
		"%160": "请正确输入要添加的媒体库路径",
		"%161": "电影",
		"%162": "电视剧",
		"%163": "视频",
		"%164": "图片",
		"%165": "添加媒体源",
		"%166": "编辑媒体源",
		"%167": "自动",
		"%168": "文件浏览",
		"%169": "检查更新",
		"%170": "下载更新",
		"%171": "安装",
		"%172": "下载失败，重新下载",
		"%173": "已是最新版本",
		"%174": "安装失败，重新安装",
		"%175": "正在下载",
		"%176": "正在安装",

		"%177": "升级",
		"%178": "升级方式",
		"%179": "自动",
		"%180": "手动",
		"%181": "升级时间:",
		"%182": "每天",
		"%183": "每周一",
		"%184": "每周二",
		"%185": "每周三",
		"%186": "每周四",
		"%187": "每周五",
		"%188": "每周六",
		"%189": "每周日",
		"%190": "当前版本",
		"%191": "正在检查更新...",
		"%192": "当前已是最新版本。",
		"%193": "发现新版本: V",
		"%194": "立即升级",
		"%195": "正在升级中，可能需要一些时间，请耐心等待...",
		"%196": "升级过程中请不要退出应用程序。",
		"%197": "正在安装新版本...",
		"%198": "升级成功",
		"%199": "升级失败，请检查网络连接。",
		"%200": "您也可以直接前往VidOn.me官方网站下载更新程序，下载地址:",
		"%201": "在",

		"%202": "客户端名称",
		"%203": "IP地址",
		"%204": "状态",
		"%205": "正在播放:",
		"%206": "媒体库资源排序规则",
		"%207": "设置此选项，则根据当地文件命名习惯对媒体资源进行排序",

		"%208": "已连接",
		"%209": "正在检测...",
		"%210": "网络异常，请稍后重试！",
		"%211": "正在切换媒体库语言...",
		"%212": "转码设置",
		"%213": "开启硬件解码编码",
		"%214": "启用硬件解码硬件编码功能，可以减轻CPU 负担，并使视频播放更流畅",
		"%215": "硬件信息",
		"%216": "您的硬件设备不能最佳支持此功能，不建议您开启此功能。",
		"%217": "显卡芯片:",
		"%218": "硬解硬编:",
		"%219": "支持",
		"%220": "不支持",
		"%221": "音轨字幕语言",
		"%222": "首选音轨语言",
		"%223": "首选字幕语言",
		"%224": "字幕显示模式",
		"%225": "自动匹配",
		"%226": "从不显示",
		"%227": "无",

		"%228": "添加媒体库",
		"%229": "自动分类",
		"%230": "家庭视频",
		"%231": "自动分配您的媒体源到相应的媒体库中",
		"%232": "扫描所选文件目录中的电影，根据电影名称获取电影详情，同时也能解析蓝光，DVD源，并在移动端播放。未能匹配的源会放入“家庭视频”媒体库中",
		"%233": "根据电视剧名称获取电影详情并解析蓝光，DVD源。命名规则为“名称-季-剧集号”的资料才能被识别",
		"%234": "所选文件目录中的视频资料或者不能根据名称匹配的电影，电视剧源都将添加到“家庭视频”媒体库中",
		"%235": "扫描所选文件夹中的图片，作为图片媒体库中的资源",
		"%236": "已选目录",
		"%237": "上一步",
		"%238": "下一步",
		"%239": "选择包含“电影”，“电视剧”，“视频”，“图片”资源的文件夹",
		"%240": "选择包含“电影”资源的文件夹",
		"%241": "选择包含“电视剧”资源的文件夹",
		"%242": "选择包含“视频”资源的文件夹",
		"%243": "选择包含“图片”资源的文件夹",
		"%244": "名称",
		"%245": "预设为所选媒体库路径的最后一级文件夹",
		"%246": "威动播放器",
		"%247": "下载移动客户端",
		"%248": "可能是移动设备上最好的视频播放器",
		"%249": "本地磁盘",
		"%250": "可移动磁盘",
		"%251": "网络驱动器",
		"%252": "媒体备份",
		"%253": "设备名称",
		"%254": "备份路径",
		"%255": "备份时间",
		"%256": "备份数量",
		"%257": "为散落的照片找个家",
		"%258": "不再为照片丢失苦恼",
		"%259": "威动云",
		"%260": "家庭多媒体管理中心",
		"%261": "威动服务器的各项功能需要配合移动端应用才能正常使用",
		"%262": "威动播放器HD用户，请先使用0.0.2.1版本 VidOn Server",
		"%263": "点击下载 VidOn Server 0021",
		"%264": "我已安装移动端App",
		"%265": "开始使用",
		"%266": "即将发布",
		"%267": "添加Windows Shared/Samba...",
		"%268": "服务器地址",
		"%269": "域",
		"%270": "用户名",
		"%271": "密码",
		"%272": "服务器信息",
		"%273": "服务器认证",
		"%274": "服务器地址错误",
		"%275": "请检查用户名和密码是否正确!",
		"%276": "访问被拒绝",
		"%277": "用户名或密码错误",
		"%278": "网络路径未找到",
		"%279": "用户中心",
		"%280": "VidOn.me账号",
		"%281": "邮箱地址",
		"%282": "会员有效期",
		"%283": "用户信息",
		"%284": "已订阅",
		"%285": "请使用在官方网站注册的VidOn.me账号登录",
		"%286": "登录",
		"%287": "注册",
		"%288": "忘记密码?"
	},
	"zh-tw": {
		"%title": "中文---l10n.js 演示",
		"%info": "你在浏览本页面的中文本地化版本。",
		"%currency": "通用",
		"%101": "媒體庫管理",
		"%102": "伺服器設置",
		"%103": "切換帳戶",
		"%104": "註銷",
		"%105": "刷新",
		"%106": "編輯",
		"%107": "刪除",
		"%108": "確定從伺服器中刪除此媒體源？",
		"%109": "刷新成功！",
		"%110": "媒體源名稱",
		"%111": "媒體源類型",
		"%112": "媒體源路徑",
		"%113": "流覽",
		"%114": "取消",
		"%115": "確定",
		"%116": "伺服器狀態",
		"%117": "通用",
		"%118": "媒體庫",
		"%119": "轉碼",
		"%120": "網路",
		"%121": "伺服器基本資訊",
		"%122": "伺服器名稱",
		"%123": "伺服器版本",
		"%124": "伺服器IP",
		"%125": "WEB埠號",
		"%126": "伺服器即時資訊",
		"%127": "當前連接用戶端",
		"%128": "CPU使用率",
		"%129": "剩餘記憶體",
		"%130": "檢查更新",
		"%131": "這個名稱將被使用於此媒體伺服器以便你網路上的其他電腦可以辨認它，如果你留空白，會默認使用你的電腦名稱。",
		"%132": "添加",
		"%133": "WEB頁面語言",
		"%134": "開機自動啟動服務",
		"%135": "保存",
		"%136": "暫存檔案路徑",
		"%137": "設置你的伺服器在轉碼時存儲暫存檔案的路徑。建議所選分區剩餘空間大於1GB",
		"%138": "CPU最大使用率",
		"%139": "流媒體埠",
		"%140": "只允許本機訪問Web管理頁面",
		"%141": "設置此選項，則只允許威動伺服器所安裝的機器訪問連結 http://localhost:32080/來管理伺服器",
		"%142": "Web埠",
		"%143": "設置Web管理頁面的訪問埠號",
		"%144": "Web管理登陸用戶名",
		"%145": "Web管理登陸密碼",
		"%146": "登陸Web管理頁面時用戶名和密碼，預設為空",
		"%147": "自動更新媒體庫時間間隔",
		"%148": "從不更新",
		"%149": "1小時",
		"%150": "12小時",
		"%151": "每天",
		"%152": "3天",
		"%153": "一周",
		"%154": "一個月",
		"%155": "獲取電影資訊語言",
		"%156": "保存資訊成功",
		"%157": "取消基本資訊",
		"%158": "取消網路設置",
		"%159": "更新全部源",
		"%160": "請正確輸入要添加的媒體庫路徑",
		"%161": "電影",
		"%162": "電視劇",
		"%163": "視頻",
		"%164": "圖片",
		"%165": "添加媒體源",
		"%166": "編輯媒體源",
		"%167": "自動",
		"%168": "檔案流覽",
		"%169": "檢查更新",
		"%170": "下載更新",
		"%171": "安裝",
		"%172": "下載失敗，重新下載",
		"%173": "已是最新版本",
		"%174": "安裝失敗，重新安裝",
		"%175": "正在下載",
		"%176": "正在安裝",
		"%177": "升級",
		"%178": "升級方式",
		"%179": "自動",
		"%180": "手動",
		"%181": "升級時間:",
		"%182": "每天",
		"%183": "每週一",
		"%184": "每週二",
		"%185": "每週三",
		"%186": "每週四",
		"%187": "每週五",
		"%188": "每週六",
		"%189": "每週日",
		"%190": "當前版本",
		"%191": "正在檢查更新...",
		"%192": "當前已是最新版本。",
		"%193": "發現新版本: V",
		"%194": "立即升級",
		"%195": "正在升級中，可能需要一些時間，請耐心等待...",
		"%196": "升級過程中請不要退出應用程式。",
		"%197": "正在安裝新版本...",
		"%198": "升級成功",
		"%199": "升級失敗，請檢查網路連接。",
		"%200": "您也可以直接前往VidOn.me官方網站下載更新程式，下載位址:",
		"%201": "在",
		"%202": "用戶端名稱",
		"%203": "IP地址",
		"%204": "狀態",
		"%205": "正在播放:",
		"%206": "媒體庫資源排序規則",
		"%207": "設定此選項，則根據當地檔案命名習慣對媒體資源進行排序",

		"%208": "連接中...",
		"%209": "正在檢測...",
		"%210": "網路異常，請稍後重試！",
		"%211": "正在切換媒體庫語言...",
		"%212": "轉碼設定",
		"%213": "開啟硬體解碼編碼",
		"%214": "啟用硬體解碼硬體編碼功能，可以減輕CPU負擔，並使視訊播放更流暢",
		"%215": "硬體資訊",
		"%216": "您的硬體設備不能最佳支援此功能，不建議您開啟此功能。",
		"%217": "顯卡晶片:",
		"%218": "硬解硬編:",
		"%219": "支援",
		"%220": "不支援",

		"%228": "添加媒體庫",
		"%229": "自動分類",
		"%230": "家庭視訊",
		"%231": "自動分配您的媒體源到相應的媒體庫中",
		"%232": "掃描所選資料目錄中的電影，根據電影名稱獲取電影詳情，同時也能解析藍光，DVD源，並在移動端播放。未能匹配的源會放入“家庭視訊”媒體庫中",
		"%233": "根據電視劇名稱獲取電影詳情並解析藍光，DVD源。命名規則為“名稱-季-劇集號”的資料才能被識別",
		"%234": "所選資料目錄中的視訊資料或者不能根據名稱匹配的電影，電視劇資源都將添加到“家庭資源”媒體庫中",
		"%235": "掃描所選資料夾中的圖片，作為圖片媒體庫中的資源",
		"%236": "已選目錄",
		"%237": "上一步",
		"%238": "下一步",
		"%239": "選擇包含“電影”，“電視劇”，“視訊”，“圖片”資源的資料夾",
		"%240": "選擇包含“電影”資源的資料夾",
		"%241": "選擇包含“電視劇”資源的資料夾",
		"%242": "選擇包含“視訊”資源的資料夾",
		"%243": "選擇包含“圖片”資源的資料夾",
		"%244": "名稱",
		"%245": "預設為所選媒體庫路徑的最後一級資料夾名稱",
		"%246": "威動伺服器",
		"%247": "下載Apps",
		"%248": "可能是行動設備上最好的視訊播放機",
		"%249": "本地磁片",
		"%250": "抽取式磁碟",
		"%251": "網路磁碟",
		"%252": "媒體備份",
		"%253": "裝置名稱",
		"%254": "備份路徑",
		"%255": "備份時間",
		"%256": "備份數量",
		"%257": "為散落的照片找個家",
		"%258": "不再為照片丟失苦惱",
		"%259": "威動雲",
		"%260": "家庭多媒體管理中心",
		"%261": "VidOn Server的各項功能需要配合行動端應用才能正常使用",
		"%262": "VidOn Player HD用戶，請先使用0.0.2.1版本VidOn Server",
		"%263": "點擊下載 VidOn Server 0021",
		"%264": "我已安裝移動端 App",
		"%265": "開始使用",
		"%266": "即將發佈",
		"%267": "添加Windows Shared/Samba...",
		"%268": "伺服器地址",
		"%269": "域",
		"%270": "用户名",
		"%271": "密碼",
		"%272": "伺服器資訊",
		"%273": "伺服器認證",
		"%274": "伺服器地址錯誤",
		"%275": "請檢查用戶名和密碼是否正確!",
		"%276": "訪問被拒絕",
		"%277": "用戶名或密碼錯誤",
		"%278": "網路路徑未找到",
		"%279": "用户中心",
		"%280": "VidOn.me帳號",
		"%281": "郵箱地址",
		"%282": "會員有效期",
		"%283": "使用者資訊",
		"%284": "已訂製",
		"%285": "請使用在官方網站註冊的VidOn.me帳號登錄",
		"%286": "登入",
		"%287": "註冊",
		"%288": "忘記密碼?"
	},
	"ja": {
		"%101": "メディアライブラリ管理",
		"%102": "サーバー設定",
		"%103": "アカウントの切替",
		"%104": "ログアウト",
		"%105": "更新",
		"%106": "編集",
		"%107": "削除",
		"%108": "サーバーからこのメディアリソースを削除しますか？",
		"%109": "更新に成功しました！",
		"%110": "メディアリソース名",
		"%111": "メディアリソースタイプ",
		"%112": "メディアリソースディレクトリー",
		"%113": "参照",
		"%114": "キャンセル",
		"%115": "確認",
		"%116": "サーバー状態",
		"%117": "汎用",
		"%118": "メデイアライブラリ",
		"%119": "トランスコーディング",
		"%120": "ネットワーク",
		"%121": "サーバーの基本情報",
		"%122": "サーバー名",
		"%123": "サーバーバージョン",
		"%124": "サーバーIP",
		"%125": "WEBポート番号",
		"%126": "サーバーリアルタイム情報",
		"%127": "現在の接続されるクライアント",
		"%128": "CPU利用率",
		"%129": "残りのメモリ",
		"%130": "アップデートをチェックします",
		"%131": "別のネットワークに接続されたコンピュータが簡単に識別できるように、その名前はこのメディアサーバー上で適用されます。それを空白のままにすると、システムはデフォルトでコンピュータ名を使用します。",
		"%132": "追加",
		"%133": "WEBページ言語",
		"%134": "システムスタートアップのスタートサービス",
		"%135": "保存",
		"%136": "一時的なファイルパス",
		"%137": "トランスコーディングしながら一時ファイルを保存するパスを設定します。選択されたパーティションは1GB以上の空き容量をお勧めします。",
		"%138": "CPUの最大利用率",
		"%139": "ストリームメディアポート",
		"%140": "このコンピュータのみはWeb管理ページにアクセスできるようにします。",
		"%141": "VidOn serverがインストールされたパソコンのみがhttp://localhost:32080/にアクセスしてサーバーを管理するように、このオプションを設定してください",
		"%142": "Webポート",
		"%143": "Web管理ページのアクセスポート番号を設定してください",
		"%144": "Web管理のユーザー名",
		"%145": "Web管理の登録パスワード",
		"%146": "Web管理ページにログインする場合のユーザー名とパスワードは、デフォルトでNullです",
		"%147": "メディアライブラリのオートアップデート時間を自動的に更新します",
		"%148": "いつでも更新しません",
		"%149": "1時間",
		"%150": "12時間",
		"%151": "毎日",
		"%152": "3日",
		"%153": "1週間",
		"%154": "1ヶ月",
		"%155": "映画情報にアクセスします",
		"%156": "情報の保存に成功しました",
		"%157": "基本情報をキャンセルします",
		"%158": "ネットワーク設定をキャンセルします",
		"%159": "すべてのメディアリソースをアップデートします",
		"%160": "対象のメディアパスを正しく入力してください",
		"%161": "映画",
		"%162": "ドラマ",
		"%163": "ビデオ",
		"%164": "画像",
		"%165": "メディアリソースを追加します",
		"%166": "メディアリソースを編集します",
		"%167": "自動",
		"%168": "ファイルブラウザ",
		"%169": "更新の確認",
		"%170": "ダウンロード更新",
		"%171": "インストール",
		"%172": "ダウンロードに失敗した、再ダウンロードしてください",
		"%173": "既に最新版です",
		"%174": "インストールに失敗した、再インストールしてください",
		"%175": "ダウンロード中",
		"%176": "インストール中",
		"%177": "アップデート",
		"%178": "アップデート方法",
		"%179": "自動",
		"%180": "手動",
		"%181": "更新頻度:",
		"%182": "毎日",
		"%183": "毎週月曜日",
		"%184": "毎週火曜日",
		"%185": "毎週水曜日",
		"%186": "毎週木曜日",
		"%187": "毎週金曜日",
		"%188": "毎週土曜日",
		"%189": "毎週日曜日",
		"%190": "現在のバージョン",
		"%191": "アップデートをチェック中…",
		"%192": "最新バージョンです",
		"%193": "新しいバージョンが利用可能: V",
		"%194": "今すぐアップデート",
		"%195": "アップデート中、少し時間がかかりますから、お待ちください…",
		"%196": "アップデート中、アプリケーションを終了しないでください。",
		"%197": "新しいバージョンをインストールしています…",
		"%198": "アップデートが完了しました。",
		"%199": "アップデートに失敗しました、ネットワークの接続状態を確認してください。",
		"%200": "VidOn.me公式サイトから最新版をダウンロードしてインストールすることも出来ます。ダウンロード先: ",
		"%201": "に",
		"%202": "クライアント名",
		"%203": "IPアドレス",
		"%204": "ステータス",
		"%205": "再生中:",
		"%206": "メディアリソースのソート基準",
		"%207": "このオプションを設定することにより、地方特有のファイルの命名規則に従ってメディアリソースをソースすることが出来ます。",
		"%208": "アクセス中...",
		"%209": "チェック中...",
		"%210": "ネットワークに異常があります、後でもう一度やり直してください！",
		"%211": "メディア ギャラリーの言語を切り替え中...",
		"%212": "トランスコードの設定",
		"%213": "ハードウェアデコード/エンコードを有効にする",
		"%214": "ハードウェアデコード/エンコードの機能を有効にすると、CPUの負担を減らすし、ビデオの再生をよりスムーズにできる",
		"%215": "ハードウェア情報",
		"%216": "ハードウェアデバイスがこの機能を最適にサポートできないため、この機能を有効しないようにお勧めします。",
		"%217": "グラフィックスチップ:",
		"%218": "ハードウェアデコード/エンコード",
		"%219": "サポートします",
		"%220": "サポートしていません",

		"%228": "メディアライブラリーにリソースを新規追加",
		"%229": "自動分類",
		"%230": "ビデオ",
		"%231": "リソースを対応するメディアライブラリーに自動分類します",
		"%232": "選択されたディレクトリにある映画をスキャンし、映画の名前によって映画の詳細情報を取得しながらブルーレイ、DVDソースを分析し、モバイルデバイス上で再生します。そのほかのソースは「ビデオ」ライブラリーに追加します",
		"%233": "テレビドラマの名前によってTVシリーズの詳細情報を取得しながらブルーレイ、DVDソースを分析します。「タイトル-シリーズ-エピソード」のようなファイル名だけが認識されます",
		"%234": "選択されたディレクトリにあるビデオファイル、タイトルが任意の映画やTVシリーズ情報と一致しない映画やTVシリーズはすべて「ビデオ」ライブラリーに追加します",
		"%235": "選択されたディレクトリにある画像をスキャンして「画像」ライブラリーに追加します",
		"%236": "選択されたディレクトリ",
		"%237": "戻る",
		"%238": "次へ",
		"%239": "「映画」、「テレビドラマ」、「ビデオ」、「画像」などのリソースを含むフォルダを選択します",
		"%240": "「映画」リソースを含むフォルダを選択します",
		"%241": "「テレビドラマ」リソースを含むフォルダを選択します",
		"%242": "「ビデオ」リソースを含むフォルダを選択します",
		"%243": "「画像」リソースを含むフォルダを選択します",
		"%244": "フォルダ名",
		"%245": "選択されたメディアライブラリーにおける最後のフォルダ名をデフォルトに設定します",
		"%246": "VidOn Player",
		"%247": "ダウンロードApps",
		"%248": "モバイルデバイスでおそらく最高の動画プレーヤー",
		"%249": "ローカルディスク",
		"%250": "リムーバブルディスク",
		"%251": "ネットワークドライブ",
		"%252": "メディアバックアップ",
		"%253": "デバイスネーム",
		"%254": "バックアップパス",
		"%255": "バックアップデータ",
		"%256": "バックアップ数",
		"%257": "散らばる写真を一括管理",
		"%258": "小さな一枚でも失うこともない",
		"%259": "VidOn Cloud",
		"%260": "ホームマルチメディア管理センター",
		"%261": "VidOn Serverの各機能は携帯端末アプリと共に動作する必要があります",
		"%262": "VidOn プレーヤー HDのユーザー様、VidOn Server 0.0.2.1を使用してください",
		"%263": "クリックしてVidOn Server 0021をダウンロード",
		"%264": "携帯端末アプリをインストールしました",
		"%265": "使用開始",
		"%266": "Available soon",
		"%267": "Windows Shared/Samba...を追加",
		"%268": "サーバーアドレス",
		"%269": "ドメイン",
		"%270": "ユーザー名",
		"%271": "パスワード",
		"%272": "サーバー情報",
		"%273": "サーバー認証",
		"%274": "サーバーアドレスが正しくないです",
		"%275": "ユーザー名とパスワードが正しいかをチェックしてください!",
		"%276": "アクセスが拒否された",
		"%277": "ユーザー名またはパスワードは正しくないです",
		"%278": "ネットワークパスが見つかりません",
		"%279": "ユーザーセンター",
		"%280": "VidOn.meアカウント",
		"%281": "メールアドレス",
		"%282": "有効期限",
		"%283": "ユーザー情報",
		"%284": "入会済",
		"%285": "公式サイトに登録したVidOn.meアカウントでログインしてください",
		"%286": "ログイン",
		"%287": "登録",
		"%288": "パスワード忘れ?"
	},
	"se": {
		"%title": "Svenska - Demo av l10n.js",
		"%info": "Du tittar p? den svenska ?vers?ttningen av denna sida",
		"%101": "Mediabibliotekshantering",
		"%102": "Serverinställningar",
		"%103": "Växla användare",
		"%104": "Logga ut",
		"%105": "Uppdatera",
		"%106": "Redigera",
		"%107": "Radera",
		"%108": "Radera de valda mediafilerna från servern?",
		"%109": "Uppdatering utförd!",
		"%110": "Medianamn",
		"%111": "Mediatyp",
		"%112": "Sökväg",
		"%113": "Bläddra",
		"%114": "Avbryt",
		"%115": "OK",
		"%116": "Serverstatus",
		"%117": "Allmänt",
		"%118": "Mediabibliotek",
		"%119": "Omkodning",
		"%120": "Nätverk",
		"%121": "Serverinformation",
		"%122": "Servernamn",
		"%123": "Serverversion",
		"%124": "Server-IP",
		"%125": "Webbportsnummer",
		"%126": "Serverinformation i realtid",
		"%127": "Klient i aktuell konfiguration",
		"%128": "Processoranvändning",
		"%129": "Återstående minne",
		"%130": "Sök efter uppdatering",
		"%131": "Namnet kommer att kopplas till den här mediaservern så att övriga nätverksdatorer enkelt kan identifera den. Om du lämnar den tom, så kommer systemet att använda ditt datornamn som standard.",
		"%132": "Lägg till",
		"%133": "Webbsidans språk",
		"%134": "Starta tjänsten vid systemuppstart.",
		"%135": "Spara",
		"%136": "Sökväg för temporära filer",
		"%137": "Ange en sökväg för att spara tillfälliga filer vid omkodning. Den valda partitionen ska ha minst 1 GB ledigt utrymme.",
		"%138": "Maximal processoranvändning",
		"%139": "Port för direktuppspelning av media",
		"%140": "Tillåt bara den här datorn att komma åt webbhanteringssidan.",
		"%141": "Om du aktiverar det här alternativet, så kommer endast datorer anslutna till VidOn-servern att vara tillåtna att komma åt http://localhost:8080/ för serverhantering.",
		"%142": "Webbport",
		"%143": "Ange portnummer för åtkomst av webbhanteringssidan",
		"%144": "Webbhanteringens användarnamn",
		"%145": "Webbhanteringens lösenord",
		"%146": "Standardvärdet för användarnamn och lösenord är tomt vid inloggning på webbhanteringssidan.",
		"%147": "Mediabibliotekets uppdateringsfrekvens",
		"%148": "Aldrig",
		"%149": "Varje timme",
		"%150": "Var 12:e timme",
		"%151": "Varje dag",
		"%152": "Var tredje dag",
		"%153": "Varje vecka",
		"%154": "Varje månad",
		"%155": "Åtkomst av filminformation",
		"%156": "Informationen sparades utan problem",
		"%157": "Avbryt standardinformation",
		"%158": "Avbryt nätverksinställningar",
		"%159": "Uppdatera alla mediaresurser",
		"%160": "Vänligen ange sökvägen för målmedia korrekt",
		"%161": "Filmer",
		"%162": "TV-program",
		"%163": "Video",
		"%164": "Bilder",
		"%165": "Lägg till mediaresurs",
		"%166": "Redigera mediaresurs",

		"%167": "Automatic",
		"%168": "File Browsing",
		"%169": "Check for Update",
		"%170": "Download Update",
		"%171": "Install",
		"%172": "Failed to download, please retry",
		"%173": "Your version is the latest",
		"%174": "Installation failed, please re-install",
		"%175": "Downloading",
		"%176": "Installing",
		"%177": "Update",
		"%178": "Update choices",
		"%179": "Auto",
		"%180": "Manual",
		"%181": "Update frequency:",
		"%182": "Everyday",
		"%183": "Every Monday",
		"%184": "Every Tuesday",
		"%185": "Every Wednesday",
		"%186": "Every Thursday",
		"%187": "Every Friday",
		"%188": "Every Saturday",
		"%189": "Every Sunday",
		"%190": "Current version",
		"%191": "Checking for update...",
		"%192": "You are running the latest version.",
		"%193": "New version is available: V",
		"%194": "Update",
		"%195": "Update in progress, please wait for a few seconds…",
		"%196": "Update in progress, please do not exit. ",
		"%197": "Installing new version...",
		"%198": "Update completed successfully.",
		"%199": "Update failed, please check your network connection.",
		"%200": "You can also download and install the new version from VidOn.me official website at:",
		"%201": "At",
		"%202": "Client Name",
		"%203": "IP Address",
		"%204": "Status",
		"%205": "Currently Playing:",
		"%206": "Sorting rules of media resources",
		"%207": "Setting up this option, you agree to sort media resources per the naming practices of local files.",
		"%208": "Connecting...",


		"%209": "Testing...",
		"%210": "Network abnormal, please retry later!",
		"%211": "Switching media library language...",
		"%212": "Transcoding Settings",
		"%213": "Enable Hardware Transcoding",
		"%214": "Hardware transcoding reduces CPU load to play back videos smoothly.",
		"%215": "Hardware Info",
		"%216": "Your hardware is not optimized for this feature, enabling this option is not recommended",
		"%217": "Graphics Card Chip:",
		"%218": "Hardware Decoding and Encoding:",
		"%219": "Supported",
		"%220": "Not Supported",

		"%228": "Add a Library",
		"%229": "Automatic Categorization",
		"%230": "Home Videos",
		"%231": "Automatically allocate your media sources into corresponding library categories",
		"%232": "Scan movies in the selected directory and collect movie info according to the movie title. DVD and Blu-ray sources can also be analyzed for playback on mobile devices. Other sources that the titles cannot match with any info will be put under “Videos” library",
		"%233": "Collect TV shows info according to the series title and analyze DVD and Blu-ray sources. Only files named in line with “Title-Season-Episode” can be recognized",
		"%234": "Media in “Videos” library are video files in a selected directory, or movies or TV shows that the titles cannot match with any movie or series info",
		"%235": "Scan the photos in the selected directory and add them to “Images” library",
		"%236": "Selected Directory",
		"%237": "Previous",
		"%238": "Next",
		"%239": "Please choose a folder including “movies”, “TV shows”, “videos” or “images”",
		"%240": "Please choose a folder including “movies”",
		"%241": "Please choose a folder including “TV shows”",
		"%242": "Please choose a folder including “videos”",
		"%243": "Please choose a folder including “images”",
		"%244": "Name",
		"%245": "The default name is the last folder name of the selected library path",
		"%246": "VidOn Player",
		"%247": "Download Apps",
		"%248": "Probably the Best Video Player on Mobile Devices",
		"%249": "Local Disk",
		"%250": "Removable Disk",
		"%251": "Network Drive",
		"%252": "Media Backup",
		"%253": "Device Name",
		"%254": "Backup Path",
		"%255": "Backup Date",
		"%256": "Number of Backups",
		"%257": "Set up a home for your scattered photos",
		"%258": "No one will get lost anymore",
		"%259": "VidOn Cloud",
		"%260": "Home Multimedia Center",
		"%261": "To use VidOn Server, make sure you've installed our mobile app on your iOS or Android devices.",
		"%262": "Dear VidOn Player HD users, VidOn Server 0.0.2.1 is ready for use now.",
		"%263": "Click to download VidOn Server 0021",
		"%264": "I've already installed the mobile app.",
		"%265": "Start VidOn Server",
		"%266": "Available soon",
		"%267": "Add Windows Shared/Samba…",
		"%268": "Server Address",
		"%269": "Domain",
		"%270": "Username",
		"%271": "Password",
		"%272": "Server Info",
		"%273": "Server Authorization",
		"%274": "Server location error",
		"%275": "Username or Password error, please try again.",
		"%276": "Access denied",
		"%277": "User name or password not recognized",
		"%278": "Network path not found",
		"%279": "User Center",
		"%280": "VidOn.me account",
		"%281": "Email address",
		"%282": "Expires on",
		"%283": "User information",
		"%284": "Subscribed",
		"%285": "Please use your official VidOn.me account to log in",
		"%286": "Log in",
		"%287": "Register",
		"%288": "Forget password?"
	}
});